version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/ebanking?authSource=admin
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=production

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongodb_data: